Update documentation
clara-parabricks/AtacWorks pull request #222
Opened 2020-11-10 18:56 UTC by ntadimeti

2020-11-10 19:12 UTC, avantikalal requested changes

2020-11-10 19:12 UTC, avantikalal commented on tutorials/pretrained_models.rst
> +To download a model and it's data, Click the link in "Model path" column in the table :ref:`Pretrained Models Table`.
it's -> its

2020-11-10 19:12 UTC, avantikalal commented on tutorials/pretrained_models.rst
>     :width: 800
Line 14: subfloder -> subfolder

2020-11-10 19:17 UTC, ntadimeti commented on tutorials/pretrained_models.rst
> +To download a model and it's data, Click the link in "Model path" column in the table :ref:`Pretrained Models Table`.
done

2020-11-10 19:17 UTC, ntadimeti commented on tutorials/pretrained_models.rst
>     :width: 800
done

2020-11-10 19:41 UTC, avantikalal requested changes

2020-11-10 19:41 UTC, avantikalal commented on tutorials/pretrained_models.rst
>  Before using these models, please note that they should only be used on data that is processed exactly as described above. If your bigWig files and/or peak calls are generated using a different metho
Can we link to tutorial 1 here?

2020-11-11 16:46 UTC, ntadimeti commented on tutorials/pretrained_models.rst
>  Before using these models, please note that they should only be used on data that is processed exactly as described above. If your bigWig files and/or peak calls are generated using a different metho
done.

2020-11-12 16:45 UTC, avantikalal approved these changes

2020-11-18 17:28 UTC, merged